version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "com.google.elemental2:*"
      - dependency-name: "com.google.guava:guava"

  - package-ecosystem: "npm"
    directory: "/app"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "bootstrap"
        versions: [">=4"]
      - dependency-name: "d3"
        versions: [">=6"]
      - dependency-name: "datatables.net-buttons"
        versions: [">=2"]

  - package-ecosystem: "npm"
    directory: "/app/local_modules/parcel-resolver-theme"
    schedule:
      interval: "daily"
