name: Test Native Binaries Build

on: workflow_dispatch

jobs:

  windows:
    runs-on: windows-2019
    name: Windows Binary
    env:
      MVN: .\mvnw.cmd --show-version --batch-mode
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2
      - name: Setup GraalVM
        id: setup-graalvm
        uses: DeLaGuardo/setup-graalvm@5.0
        with:
          graalvm: 22.0.0.2
          java: java11
      - name: Read Version
        id: read-version
        run: |
          $version = (.\mvnw.cmd help:evaluate -Dexpression=project.version --non-recursive --quiet -DforceStdout) | Out-String
          echo "::set-output name=version::$version"
        shell: powershell
      - name: Install Native Image
        id: install-native-image
        run: gu.cmd install native-image
      - name: Configure Pagefile
        id: configure-pagefile
        uses: al-cheb/configure-pagefile-action@v1.2
      - name: Build
        id: build
        run: cmd /c 'call "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvars64.bat" && .\mvnw.cmd package -Pnative'
      - name: Output
        id: output
        run: cmd /c 'dir standalone\target'
